### ISSUE TITLE
Automatically set up a web server for mock run

### ISSUE THREAD

**Issue by rht** [limikael/tonopah#1]
Currently, when I do `npm run dev:mock`, I have to also run a web server to be able to access the game. It would be great if, `npm run` also runs a web server automatically.

**Comment by limikael** [comment]
Yey! Now it sets up a webserver with all the test cases. Check it!

**Comment by rht** [comment]
Which commit(s) implemented the feature?

**Comment by limikael** [comment]
This one:

https://github.com/limikael/tonopah/commit/2cc7d6a08e0f645fbb2e3abdd32fc1de44c3965a
